// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://edguowimanbdjyubspas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZ3Vvd2ltYW5iZGp5dWJzcGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNzg2NzcsImV4cCI6MjA3ODg1NDY3N30.ggQBZZOoUrvmyQ-1HAuabrrJdW6KnSyaEHNddYkGRsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);